export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const INCREASE_ITEM_TO_BASKET = "INCREASE_ITEM_TO_BASKET";
export const DESCREASE_ITEM_FROM_BASKET = "DESCREASE_ITEM_FROM_BASKET";
export const ADD_LOCAL_DATA_TO_BASKET = "ADD_LOCAL_DATA_TO_BASKET";

